from django.urls import path

from api.views import core, endpoints

urlpatterns = [
    path('', core.api_root, name='api-root'),
    path('health/', core.health_check, name='health-check'),
    path('health', core.health_check, name='health-check-no-slash'),
    path('profile/', endpoints.profile, name='profile'),
    path('profile', endpoints.profile, name='profile-no-slash'),
    path('about/', endpoints.about, name='about'),
    path('about', endpoints.about, name='about-no-slash'),
    path('timeline/', endpoints.timeline_list, name='timeline-list'),
    path('timeline', endpoints.timeline_list, name='timeline-list-no-slash'),
    path('timeline/<int:id>/', endpoints.timeline_detail, name='timeline-detail'),
    path('timeline/<int:id>', endpoints.timeline_detail, name='timeline-detail-no-slash'),
    path('skills/', endpoints.skills_list, name='skills-list'),
    path('skills', endpoints.skills_list, name='skills-list-no-slash'),
    path('skills/<int:id>/', endpoints.skill_detail, name='skill-detail'),
    path('skills/<int:id>', endpoints.skill_detail, name='skill-detail-no-slash'),
    path('projects/', endpoints.projects_list, name='projects-list'),
    path('projects', endpoints.projects_list, name='projects-list-no-slash'),
    path('projects/<int:id>/', endpoints.project_detail, name='project-detail'),
    path('projects/<int:id>', endpoints.project_detail, name='project-detail-no-slash'),
    path('blog/', endpoints.blog_list, name='blog-list'),
    path('blog', endpoints.blog_list, name='blog-list-no-slash'),
    path('blog/<int:id>/', endpoints.blog_detail, name='blog-detail'),
    path('blog/<int:id>', endpoints.blog_detail, name='blog-detail-no-slash'),
    path('contact/', endpoints.contact, name='contact'),
    path('contact', endpoints.contact, name='contact-no-slash'),
    path('contact/messages/', endpoints.get_contact_messages, name='contact-messages'),
    path('contact/messages', endpoints.get_contact_messages, name='contact-messages-no-slash'),
    path('auth/login/', endpoints.login, name='auth-login'),
    path('auth/login', endpoints.login, name='auth-login-no-slash'),
    path('auth/logout/', endpoints.logout, name='auth-logout'),
    path('auth/logout', endpoints.logout, name='auth-logout-no-slash'),
    path('auth/check/', endpoints.check_auth, name='auth-check'),
    path('auth/check', endpoints.check_auth, name='auth-check-no-slash'),
    path('user/', endpoints.get_public_user_info, name='user-public'),
    path('user', endpoints.get_public_user_info, name='user-public-no-slash'),
    path('admin/user/password/', endpoints.change_password, name='admin-user-password'),
    path('admin/user/password', endpoints.change_password, name='admin-user-password-no-slash'),
    path('admin/user/', endpoints.admin_user, name='admin-user'),
    path('admin/user', endpoints.admin_user, name='admin-user-no-slash'),
    path('user/social-links/', endpoints.user_social_links, name='user-social-links'),
    path('user/social-links', endpoints.user_social_links, name='user-social-links-no-slash'),
    path('user/social-links/<int:id>/', endpoints.user_social_link_detail, name='user-social-link-detail'),
    path('user/social-links/<int:id>', endpoints.user_social_link_detail, name='user-social-link-detail-no-slash'),
    path('upload/profile-image/', endpoints.upload_profile_image, name='upload-profile-image'),
    path('upload/profile-image', endpoints.upload_profile_image, name='upload-profile-image-no-slash'),
    path('upload/delete-profile-image/', endpoints.delete_profile_image, name='delete-profile-image'),
    path('upload/delete-profile-image', endpoints.delete_profile_image, name='delete-profile-image-no-slash'),
]
